[agent]
  interval = "5s"
  round_interval = true

[[inputs.mqtt_consumer]]
  servers = ["tcp://secvis_mosquitto:1883"]
  topics = ["pt_epson/edge/resource"]
  data_format = "json"
  name_override = "edge_resource"
  tag_keys = ["device_name", "rtsp_status", "edge_status"]

[[outputs.influxdb_v2]]
  urls = ["http://secvis_influxdb:8086"]
  token = "${INFLUXDB_TOKEN}"
  organization = "epson"
  bucket = "resource_monitoring"